[holbuild]
minimum_version = "0.10.3"

[project]
name = "vyper-hol"
version = "0.2.2"

[build]
roots = ["vyperHolScript.sml", "semantics/vyperCheckContractLibTestScript.sml", "frontend/vyperCheckContractFrontendLibTestScript.sml", "tests/vyperCheckContractTraceLibTestScript.sml"]

[dependencies.verifereum]
git = "https://github.com/verifereum/verifereum.git"
rev = "20ed6a42ca322a7a3809aa487a65856cabb992b0"
