[holbuild]
minimum_version = "0.11.3"

[project]
name = "vyper-hol"
version = "0.2.3"

[build]
roots = ["vyperHolScript.sml",
         "semantics/vyperCheckContractLibTestScript.sml",
         "frontend/vyperCheckContractFrontendLibTestScript.sml",
         "tests/vyperCheckContractTraceLibTestScript.sml"]

[build.theory_tactic_timeouts]
"semantics/vyperInterpreterScript.sml" = 5
"semantics/prop/vyperLogPreservationScript.sml" = 5

[dependencies.verifereum]
git = "https://github.com/verifereum/verifereum.git"
rev = "0fa9a9129e1efb146f3020a39faf40d14867c6b4"
