(*
 * Plan well-formedness: prefix_wf for code generator output
 *
 * Proves that ops generated by generate_regular_inst_plan's
 * prefix (before the final SOEmit) satisfy prefix_wf,
 * enabling prefix_sim to establish AsmOK.
 *
 * Key results:
 *   - prefix_wf_append: composition of prefix_wf sequences
 *   - prefix_wf_every_prefix_op: prefix_wf implies EVERY is_prefix_op
 *   - stack_find_bound: stack_find results are within bounds
 *   - prefix_wf_spills/restores: prefix_wf for bulk spill/restore
 *   - do_swap_wf, do_dup_wf, etc: per-operation wf
 *   - regular_plan_prefix_wf_gen: the main result
 *)


Theory planWf
Ancestors
  prefixExec prefixSim stackPlanOps stackPlanGen stackModel stackPlanTypes codegenRel asmIR list rich_list arithmetic pair option
Libs
  BasicProvers

(* ===== Basic prefix_wf properties ===== *)

Theorem prefix_wf_nil[simp]:
  !lo n. prefix_wf lo n []
Proof
  simp[prefix_wf_def]
QED

Theorem prefix_end_len_nil[simp]:
  !lo n. prefix_end_len lo n [] = n
Proof
  simp[prefix_end_len_def]
QED

Theorem prefix_wf_append:
  !xs ys lo n.
    prefix_wf lo n xs /\
    prefix_wf lo (prefix_end_len lo n xs) ys ==>
    prefix_wf lo n (xs ++ ys)
Proof
  Induct >> simp[prefix_wf_def, prefix_end_len_def] >>
  rpt gen_tac >> pairarg_tac >> simp[] >> metis_tac[]
QED

Theorem prefix_end_len_append:
  !xs ys lo n.
    prefix_end_len lo n (xs ++ ys) =
    prefix_end_len lo (prefix_end_len lo n xs) ys
Proof
  Induct >> simp[prefix_end_len_def] >>
  rpt gen_tac >> simp[prefix_end_len_def] >>
  pairarg_tac >> simp[]
QED

Theorem prefix_wf_every_prefix_op:
  !ops lo n. prefix_wf lo n ops ==> EVERY is_prefix_op ops
Proof
  Induct >> simp[prefix_wf_def] >>
  rpt gen_tac >> pairarg_tac >> simp[] >>
  rpt strip_tac >>
  Cases_on `h` >> fs[stack_op_wf_def, is_prefix_op_def] >>
  metis_tac[]
QED

Theorem prefix_wf_cons:
  !op rest lo n.
    prefix_wf lo n (op :: rest) <=>
    (let (ok, n') = stack_op_wf lo op n in
     ok /\ prefix_wf lo n' rest)
Proof
  simp[prefix_wf_def]
QED

Theorem prefix_wf_single:
  !op lo n. prefix_wf lo n [op] <=> FST (stack_op_wf lo op n)
Proof
  rpt gen_tac >> simp[prefix_wf_def] >>
  pairarg_tac >> simp[]
QED

(* prefix_end_len for single ops *)
Theorem prefix_end_len_single:
  !op lo n. prefix_end_len lo n [op] = SND (stack_op_wf lo op n)
Proof
  rpt gen_tac >> simp[prefix_end_len_def] >>
  pairarg_tac >> simp[]
QED

(* prefix_end_len for concrete ops *)
Theorem prefix_end_len_spill[simp]:
  !lo off n. prefix_end_len lo n [SOSpill off] = n - 1
Proof
  simp[prefix_end_len_def, stack_op_wf_def]
QED

Theorem prefix_end_len_restore[simp]:
  !lo off n. prefix_end_len lo n [SORestore off] = n + 1
Proof
  simp[prefix_end_len_def, stack_op_wf_def]
QED

Theorem prefix_end_len_swap[simp]:
  !lo k n. prefix_end_len lo n [SOSwap k] = n
Proof
  simp[prefix_end_len_def, stack_op_wf_def]
QED

Theorem prefix_end_len_dup[simp]:
  !lo k n. prefix_end_len lo n [SODup k] = n + 1
Proof
  simp[prefix_end_len_def, stack_op_wf_def]
QED

Theorem prefix_end_len_push_lit[simp]:
  !lo v n. prefix_end_len lo n [SOPush (Lit v)] = n + 1
Proof
  simp[prefix_end_len_def, stack_op_wf_def]
QED

Theorem prefix_end_len_poke[simp]:
  !lo i op n. prefix_end_len lo n [SOPoke i op] = n
Proof
  simp[prefix_end_len_def, stack_op_wf_def]
QED

(* ===== stack_find / stack_get_depth bounds ===== *)

Theorem stack_find_bound:
  !p xs d. stack_find p xs = SOME d ==> d < LENGTH xs
Proof
  Induct_on `xs` >> simp[stack_find_def] >>
  rpt gen_tac >> IF_CASES_TAC >> simp[] >>
  Cases_on `stack_find p xs` >> simp[] >>
  strip_tac >> gvs[] >> res_tac >> simp[]
QED

Theorem stack_get_depth_bound:
  !op stk d.
    stack_get_depth op stk = SOME d ==> d < LENGTH stk
Proof
  rpt strip_tac >>
  fs[stack_get_depth_def] >>
  imp_res_tac stack_find_bound >>
  fs[LENGTH_REVERSE]
QED

(* ===== Bulk spill/restore prefix_wf ===== *)

(* A list of k SOSpill ops is prefix_wf when starting stack >= k *)
Theorem prefix_wf_spills:
  !offs lo n.
    LENGTH offs <= n ==>
    prefix_wf lo n (MAP SOSpill offs) /\
    prefix_end_len lo n (MAP SOSpill offs) = n - LENGTH offs
Proof
  Induct >> simp[] >>
  rpt gen_tac >> strip_tac >>
  simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def] >>
  first_x_assum (qspecl_then [`lo`, `n - 1`] mp_tac) >>
  simp[]
QED

(* A list of k SORestore ops is always prefix_wf *)
Theorem prefix_wf_restores:
  !offs lo n.
    prefix_wf lo n (MAP SORestore offs) /\
    prefix_end_len lo n (MAP SORestore offs) = n + LENGTH offs
Proof
  Induct >> simp[] >>
  rpt gen_tac >>
  simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def] >>
  first_x_assum (qspecl_then [`lo`, `n + 1`] mp_tac) >> simp[]
QED

(* ===== Helper: emit_input_plan / reorder_plan with empty args ===== *)

Theorem emit_input_plan_nil[simp]:
  !opc lv ps. emit_input_plan opc [] lv ps = ([], ps)
Proof
  simp[emit_input_plan_def]
QED

Theorem reorder_plan_nil[simp]:
  !dfg ps. reorder_plan dfg [] ps = ([], ps)
Proof
  simp[reorder_plan_def]
QED

(* ===== Stack length helpers ===== *)

Theorem stack_swap_length[simp]:
  !dist stk. LENGTH (stack_swap dist stk) = LENGTH stk
Proof
  simp[stack_swap_def, LENGTH_LUPDATE]
QED

Theorem stack_dup_length:
  !dist stk. dist < LENGTH stk ==>
    LENGTH (stack_dup dist stk) = LENGTH stk + 1
Proof
  simp[stack_dup_def, stack_push_def]
QED

Theorem stack_push_length[simp]:
  !x stk. LENGTH (stack_push x stk) = LENGTH stk + 1
Proof
  simp[stack_push_def]
QED

Theorem stack_pop_length[simp]:
  !k stk. k <= LENGTH stk ==>
    LENGTH (stack_pop k stk) = LENGTH stk - k
Proof
  simp[stack_pop_def, LENGTH_TAKE_EQ]
QED

(* ===== Combined wf+len theorems =====
 *
 * Each operation gets ONE theorem giving BOTH:
 *   prefix_wf lo (LENGTH ps.ps_stack) ops
 *   prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
 * This eliminates duplicate case analysis and makes composition trivial.
 *)

(* ----- do_restore: wf + len ----- *)

Theorem do_restore_wf_len:
  !op ps lo.
    let (ops, ps') = do_restore op ps in
      prefix_wf lo (LENGTH ps.ps_stack) ops /\
      prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  rpt gen_tac >>
  simp[do_restore_def] >>
  Cases_on `FLOOKUP ps.ps_spilled op` >>
  simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def, stack_push_def]
QED

(* ----- do_spill_tos: wf + len ----- *)

Theorem do_spill_tos_wf_len:
  !ps lo.
    1 <= LENGTH ps.ps_stack ==>
    let (ops, ps') = do_spill_tos ps in
      prefix_wf lo (LENGTH ps.ps_stack) ops /\
      prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  rpt strip_tac >>
  simp[do_spill_tos_def] >>
  pairarg_tac >> simp[] >>
  pairarg_tac >> gvs[] >>
  simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def,
       stack_pop_def, LENGTH_TAKE_EQ]
QED

(* ----- do_spill_at: wf + len ----- *)

Theorem do_spill_at_wf_len:
  !dist ps lo.
    dist <= 16 /\ dist < LENGTH ps.ps_stack /\
    1 <= LENGTH ps.ps_stack ==>
    let (ops, ps') = do_spill_at dist ps in
      prefix_wf lo (LENGTH ps.ps_stack) ops /\
      prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  rpt strip_tac >>
  Cases_on `dist = 0`
  >- (
    simp[do_spill_at_def] >>
    qspecl_then [`ps`, `lo`] mp_tac do_spill_tos_wf_len >>
    simp[] >> pairarg_tac >> simp[]
  ) >>
  (* dist > 0, dist <= 16: [SOSwap dist] ++ spill_ops *)
  simp[do_spill_at_def] >>
  pairarg_tac >> simp[] >>
  qspecl_then [`ps with ps_stack := stack_swap dist ps.ps_stack`,
               `lo`] mp_tac do_spill_tos_wf_len >>
  simp[] >> pairarg_tac >> gvs[] >> strip_tac >>
  simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def]
QED

(* ----- Shared: spill FOLDL decomposition -----
 * do_swap deep and do_dup deep both use the same FOLDL to spill items.
 * spill_foldl_form: ops = acc_ops ++ MAP SOSpill new_offs,
   offs = acc_offs ++ new_offs, LENGTH new_offs = LENGTH items.
   We express this with ∃new_offs to avoid tracking intermediate state. *)
Theorem spill_foldl_form[local]:
  !items acc_ops acc_offs al0 ops offs al'.
    FOLDL (\(ops, offs, al) (item:operand).
      let (off, al') = alloc_spill_slot al in
      (ops ++ [SOSpill off], SNOC off offs, al'))
      (acc_ops, acc_offs, al0) items = (ops, offs, al') ==>
    ?new_offs.
      offs = acc_offs ++ new_offs /\
      ops = acc_ops ++ MAP SOSpill new_offs /\
      LENGTH new_offs = LENGTH items
Proof
  Induct >- (simp[] >> metis_tac[APPEND_NIL]) >>
  rpt gen_tac >> simp[Once FOLDL] >>
  Cases_on `alloc_spill_slot al0` >> simp[LET_THM] >>
  strip_tac >>
  qpat_x_assum `!a b c d e f. _ ==> _`
    (mp_tac o SIMP_RULE bool_ss [LET_THM]) >>
  disch_then drule >> strip_tac >>
  qexists_tac `q :: new_offs` >>
  ASM_REWRITE_TAC[MAP, LENGTH, APPEND] >>
  simp[SNOC_APPEND, GSYM APPEND_ASSOC]
QED

(* Corollary: starting from empty accumulators *)
Theorem spill_foldl_form_nil[local]:
  !items al0 ops offs al'.
    FOLDL (\(ops, offs, al) (item:operand).
      let (off, al') = alloc_spill_slot al in
      (ops ++ [SOSpill off], SNOC off offs, al'))
      ([], [], al0) items = (ops, offs, al') ==>
    ops = MAP SOSpill offs /\
    LENGTH offs = LENGTH items
Proof
  rpt strip_tac >> drule spill_foldl_form >>
  strip_tac >> gvs[]
QED

(* ----- Shared: spill+restore prefix_wf -----
 * Both deep swap and deep dup produce spill_ops ++ restore_ops
 * where spill_ops = MAP SOSpill offsets, restore_ops = MAP SORestore ....
 * This gives prefix_wf for the composition. *)
Theorem spill_restore_prefix_wf[local]:
  !spill_offs restore_offs lo n.
    LENGTH spill_offs <= n ==>
    prefix_wf lo n (MAP SOSpill spill_offs ++
                     MAP SORestore restore_offs) /\
    prefix_end_len lo n (MAP SOSpill spill_offs ++
                          MAP SORestore restore_offs) =
      n - LENGTH spill_offs + LENGTH restore_offs
Proof
  rpt gen_tac >> strip_tac >>
  `prefix_wf lo n (MAP SOSpill spill_offs) /\
   prefix_end_len lo n (MAP SOSpill spill_offs) = n - LENGTH spill_offs` by
    simp[prefix_wf_spills] >>
  `prefix_wf lo (n - LENGTH spill_offs) (MAP SORestore restore_offs) /\
   prefix_end_len lo (n - LENGTH spill_offs) (MAP SORestore restore_offs) =
     n - LENGTH spill_offs + LENGTH restore_offs` by
    simp[prefix_wf_restores] >>
  metis_tac[prefix_wf_append, prefix_end_len_append]
QED

(* ----- Shared: spill+restore (indexed form) -----
 * Both deep swap and deep dup produce:
 *   MAP SOSpill offs ++ MAP (λidx. SORestore (EL idx offs)) idxs
 * This helper handles the MAP composition so callers don't need to. *)
Theorem spill_restore_indexed_wf[local]:
  !offs idxs lo n.
    LENGTH offs <= n ==>
    prefix_wf lo n (MAP SOSpill offs ++
                     MAP (\idx. SORestore (EL idx offs)) idxs) /\
    prefix_end_len lo n (MAP SOSpill offs ++
                          MAP (\idx. SORestore (EL idx offs)) idxs) =
      n - LENGTH offs + LENGTH idxs
Proof
  rpt gen_tac >> strip_tac >>
  `MAP (\idx. SORestore (EL idx offs)) idxs =
   MAP SORestore (MAP (\idx. EL idx offs) idxs)` by
    (Induct_on `idxs` >> simp[]) >>
  simp[] >>
  qspecl_then [`offs`, `MAP (\idx. EL idx offs) idxs`, `lo`, `n`]
    mp_tac spill_restore_prefix_wf >>
  simp[LENGTH_MAP]
QED

(* ----- do_swap: wf + len ----- *)

Theorem do_swap_wf_len:
  !dist ps lo.
    dist < LENGTH ps.ps_stack ==>
    let (ops, ps') = do_swap dist ps in
      prefix_wf lo (LENGTH ps.ps_stack) ops /\
      prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  rpt strip_tac >>
  Cases_on `dist = 0`
  >- (gvs[do_swap_def])
  >>
  Cases_on `dist <= 16`
  >- (
    gvs[do_swap_def] >>
    simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def]
  )
  >>
  simp[do_swap_def] >>
  qabbrev_tac `items = top_n (dist + 1) ps.ps_stack` >>
  qabbrev_tac `fres = FOLDL
    (\(ops,offs,al) (item:operand).
      (\(off,al'). (ops ++ [SOSpill off], SNOC off offs, al'))
        (alloc_spill_slot al)) ([],[],ps.ps_alloc) items` >>
  PairCases_on `fres` >> simp[] >>
  (* Get FOLDL properties from the Abbrev *)
  `fres0 = MAP SOSpill fres1 /\ LENGTH fres1 = LENGTH items` by
    (qpat_x_assum `Abbrev ((fres0,_,_) = _)`
       (strip_assume_tac o GSYM o REWRITE_RULE [markerTheory.Abbrev_def]) >>
     drule (SIMP_RULE bool_ss [LET_THM] spill_foldl_form_nil) >> simp[]) >>
  `LENGTH items = dist + 1` by
    (fs[Abbr `items`, top_n_def, LENGTH_TAKE_EQ]) >>
  gvs[] >>
  (* Combine the restore ops into one MAP *)
  `MAP (\idx. SORestore (EL idx fres1))
     (REVERSE (GENLIST (\i. i + 1) (dist - 1) ++ [0])) ++
   [SORestore (EL dist fres1)] =
   MAP (\idx. SORestore (EL idx fres1))
     (REVERSE (GENLIST (\i. i + 1) (dist - 1) ++ [0]) ++ [dist])` by
    simp[] >>
  ASM_REWRITE_TAC [] >> pop_assum kall_tac >>
  REWRITE_TAC [GSYM APPEND_ASSOC] >>
  qabbrev_tac `all_idxs =
    REVERSE (GENLIST (\i. i + 1) (dist - 1) ++ [0]) ++ [dist]` >>
  qspecl_then [`fres1`, `all_idxs`, `lo`, `LENGTH ps.ps_stack`]
    mp_tac spill_restore_indexed_wf >>
  impl_tac >- simp[] >>
  simp[Abbr `all_idxs`, LENGTH_APPEND, LENGTH_REVERSE,
       LENGTH_GENLIST]
QED

(* ----- do_dup: wf + len ----- *)

Theorem do_dup_wf_len:
  !dist ps lo.
    dist < LENGTH ps.ps_stack ==>
    let (ops, ps') = do_dup dist ps in
      prefix_wf lo (LENGTH ps.ps_stack) ops /\
      prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  rpt strip_tac >>
  Cases_on `dist <= 15`
  >- (
    simp[do_dup_def, stack_dup_length] >>
    simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def]
  ) >>
  (* Deep case: dist > 15. Same pattern as do_swap deep:
     spill all dist+1 items, restore dist+2 items (dup adds 1). *)
  simp[do_dup_def] >>
  qabbrev_tac `items = top_n (dist + 1) ps.ps_stack` >>
  qabbrev_tac `fres = FOLDL
    (\(ops,offs,al) (item:operand).
      (\(off,al'). (ops ++ [SOSpill off], SNOC off offs, al'))
        (alloc_spill_slot al)) ([],[],ps.ps_alloc) items` >>
  PairCases_on `fres` >> simp[] >>
  `fres0 = MAP SOSpill fres1 /\ LENGTH fres1 = LENGTH items` by
    (qpat_x_assum `Abbrev ((fres0,_,_) = _)`
       (strip_assume_tac o GSYM o REWRITE_RULE [markerTheory.Abbrev_def]) >>
     drule (SIMP_RULE bool_ss [LET_THM] spill_foldl_form_nil) >> simp[]) >>
  `LENGTH items = dist + 1` by
    (fs[Abbr `items`, top_n_def, LENGTH_TAKE_EQ]) >>
  gvs[] >>
  (* Restore ops already in MAP form; apply spill_restore_indexed_wf *)
  qabbrev_tac `all_idxs =
    REVERSE (GENLIST I (dist + 1) ++ [0])` >>
  qspecl_then [`fres1`, `all_idxs`, `lo`, `LENGTH ps.ps_stack`]
    mp_tac spill_restore_indexed_wf >>
  impl_tac >- simp[] >>
  simp[Abbr `all_idxs`, LENGTH_APPEND, LENGTH_REVERSE,
       LENGTH_GENLIST, LENGTH_TAKE_EQ]
QED

(* ----- Composition helper ----- *)

(* Combines prefix_wf_append + prefix_end_len_append in one step *)
Theorem prefix_wf_len_append:
  !ops1 ops2 lo n m k.
    prefix_wf lo n ops1 /\ prefix_end_len lo n ops1 = m /\
    prefix_wf lo m ops2 /\ prefix_end_len lo m ops2 = k ==>
    prefix_wf lo n (ops1 ++ ops2) /\
    prefix_end_len lo n (ops1 ++ ops2) = k
Proof
  metis_tac[prefix_wf_append, prefix_end_len_append]
QED

(* ----- emit_one_input: combined wf + len ----- *)

(* Using FST/SND form to avoid UNCURRY beta-reduction issues.
   Strategy: Cases_on the result pair first, then unfold definition with fs. *)
Theorem emit_one_input_wf_len:
  !opc next_liveness op ps lo.
    opc <> INVOKE ==>
    (!l. op = Label l ==> IS_SOME (FLOOKUP lo l)) ==>
    prefix_wf lo (LENGTH ps.ps_stack)
      (FST (emit_one_input opc next_liveness op ps)) /\
    prefix_end_len lo (LENGTH ps.ps_stack)
      (FST (emit_one_input opc next_liveness op ps)) =
      LENGTH (SND (emit_one_input opc next_liveness op ps)).ps_stack
Proof
  rpt gen_tac >> rpt disch_tac >>
  (* Bind the result pair to get clean goals *)
  Cases_on `emit_one_input opc next_liveness op ps` >> simp[] >>
  rename1 `emit_one_input _ _ _ _ = (ops, ps1)` >>
  Cases_on `op`
  (* Lit *)
  >- (
    gvs[emit_one_input_def, is_var_operand_def, LET_THM, stack_push_def] >>
    simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def]
  )
  (* Var *)
  >- (rename1 `Var v` >> suspend "var")
  (* Label *)
  >- (
    rename1 `Label l` >>
    gvs[emit_one_input_def, is_var_operand_def, LET_THM, stack_push_def] >>
    simp[prefix_wf_def, prefix_end_len_def, stack_op_wf_def]
  )
QED

Resume emit_one_input_wf_len[var]:
  Cases_on `FLOOKUP ps.ps_spilled (Var v)` >>
  gvs[emit_one_input_def, is_var_operand_def, LET_THM]
  >- suspend "var_none"
  >> suspend "var_some"
QED

Resume emit_one_input_wf_len[var_none]:
  (* FLOOKUP = NONE: lambda reduced, no restore. Goal has IF/case directly *)
  Cases_on `MEM v next_liveness` >> gvs[] >>
  Cases_on `stack_get_depth (Var v) ps.ps_stack` >> gvs[] >>
  rename1 `_ = SOME dist` >>
  Cases_on `do_dup dist ps` >> gvs[UNCURRY_DEF] >>
  imp_res_tac stack_get_depth_bound >>
  qspecl_then [`dist`, `ps`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] do_dup_wf_len) >> simp[]
QED

Resume emit_one_input_wf_len[var_some]:
  (* FLOOKUP = SOME: need Cases_on do_restore to make pair concrete *)
  Cases_on `do_restore (Var v) ps` >>
  gvs[UNCURRY_DEF] >>
  rename1 `do_restore _ _ = (r_ops, ps1')` >>
  Cases_on `MEM v next_liveness` >> gvs[]
  >- suspend "var_some_live"
  >> qspecl_then [`Var v`, `ps`, `lo`]
       mp_tac (REWRITE_RULE [LET_THM] do_restore_wf_len) >> simp[]
QED

Resume emit_one_input_wf_len[var_some_live]:
  Cases_on `stack_get_depth (Var v) ps1'.ps_stack` >> gvs[]
  >- (
    qspecl_then [`Var v`, `ps`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] do_restore_wf_len) >> simp[]
  ) >>
  rename1 `_ = SOME dist` >>
  Cases_on `do_dup dist ps1'` >> gvs[UNCURRY_DEF] >>
  rename1 `do_dup _ _ = (d_ops, ps2)` >>
  imp_res_tac stack_get_depth_bound >>
  qspecl_then [`Var v`, `ps`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] do_restore_wf_len) >> simp[] >>
  strip_tac >>
  qspecl_then [`dist`, `ps1'`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] do_dup_wf_len) >> simp[] >>
  strip_tac >>
  irule prefix_wf_len_append >> metis_tac[]
QED

Finalise emit_one_input_wf_len;

(* ===== emit_input_plan: structural traversal of emit_one_input ===== *)

Theorem emit_input_plan_wf_len:
  !operands opc next_liveness ps lo.
    opc <> INVOKE ==>
    (!l. MEM (Label l) operands ==> IS_SOME (FLOOKUP lo l)) ==>
    prefix_wf lo (LENGTH ps.ps_stack)
      (FST (emit_input_plan opc operands next_liveness ps)) /\
    prefix_end_len lo (LENGTH ps.ps_stack)
      (FST (emit_input_plan opc operands next_liveness ps)) =
      LENGTH (SND (emit_input_plan opc operands next_liveness ps)).ps_stack
Proof
  Induct
  >- simp[emit_input_plan_def, prefix_wf_def, prefix_end_len_def] >>
  rpt gen_tac >> rpt disch_tac >>
  Cases_on `emit_one_input opc (operand_vars operands ++ next_liveness) h ps` >>
  rename1 `emit_one_input _ _ h _ = (h_ops, ps1)` >>
  Cases_on `emit_input_plan opc operands next_liveness ps1` >>
  rename1 `emit_input_plan _ operands _ _ = (rest_ops, ps2)` >>
  `prefix_wf lo (LENGTH ps.ps_stack) h_ops /\
   prefix_end_len lo (LENGTH ps.ps_stack) h_ops = LENGTH ps1.ps_stack` by
    (qspecl_then [`opc`, `operand_vars operands ++ next_liveness`, `h`, `ps`, `lo`]
       mp_tac (REWRITE_RULE [LET_THM] emit_one_input_wf_len) >>
     simp[] >>
     (impl_tac >- (rpt strip_tac >> gvs[])) >>
     simp[]) >>
  `prefix_wf lo (LENGTH ps1.ps_stack) rest_ops /\
   prefix_end_len lo (LENGTH ps1.ps_stack) rest_ops = LENGTH ps2.ps_stack` by
    (first_x_assum (qspecl_then [`opc`, `next_liveness`, `ps1`, `lo`] mp_tac) >>
     simp[]) >>
  gvs[emit_input_plan_def] >>
  metis_tac[prefix_wf_append, prefix_end_len_append]
QED

(* ===== reduce_depth_plan: iterated spills ===== *)

(* FIND P l = SOME x implies MEM x l *)
Theorem find_mem[local]:
  !P l x. FIND P l = SOME x ==> MEM x l
Proof
  Induct_on `l` >> simp[FIND_thm] >>
  rpt gen_tac >> IF_CASES_TAC >> simp[] >>
  metis_tac[]
QED

(* select_spill_candidate returns a value ≤ 16 and < LENGTH stk *)
Theorem select_spill_candidate_bound:
  !stk forbidden target_dist target_len cand.
    1 <= LENGTH stk ==>
    select_spill_candidate stk forbidden target_dist target_len = SOME cand ==>
    cand <= 16 /\ cand < LENGTH stk
Proof
  rpt gen_tac >> rpt disch_tac >>
  fs[select_spill_candidate_def, LET_THM] >>
  imp_res_tac find_mem >>
  fs[MEM_GENLIST] >>
  qpat_x_assum `FIND _ _ = _` kall_tac >>
  qabbrev_tac `mx = MIN 16 (MIN (target_dist - 1) (LENGTH stk - 1))` >>
  `mx <= 16 /\ mx < LENGTH stk` by
    (unabbrev_all_tac >> simp[MIN_DEF]) >>
  simp[]
QED

Theorem select_spill_candidate_below_target:
  !stk forbidden target_dist target_len cand.
    select_spill_candidate stk forbidden target_dist target_len = SOME cand ==>
    target_len <= cand
Proof
  rpt strip_tac >> fs[select_spill_candidate_def, LET_THM] >>
  imp_res_tac FIND_SOME_MEM >> gvs[]
QED

(* stack_get_depth = SOME implies stack is non-empty *)
Theorem stack_get_depth_nonempty[local]:
  !op stk d. stack_get_depth op stk = SOME d ==> 1 <= LENGTH stk
Proof
  rpt strip_tac >>
  imp_res_tac stack_get_depth_bound >> simp[]
QED

Theorem reduce_depth_plan_wf_len:
  !fuel target_ops target_op f target_len ps lo.
    let (ops, ps') =
      reduce_depth_plan fuel target_ops target_op f target_len ps in
    prefix_wf lo (LENGTH ps.ps_stack) ops /\
    prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  Induct >> simp[reduce_depth_plan_def, LET_THM] >>
  rpt gen_tac >>
  Cases_on `stack_get_unfixed_depth target_op f target_len ps.ps_stack` >>
  simp[] >>
  IF_CASES_TAC >> simp[] >>
  IF_CASES_TAC >> simp[] >>
  Cases_on `select_spill_candidate ps.ps_stack target_ops x target_len` >>
  simp[] >> simp[LET_THM] >>
  Cases_on `do_spill_at x' ps` >> gvs[UNCURRY_DEF] >>
  rename1 `do_spill_at _ _ = (s_ops, ps1)` >>
  Cases_on `reduce_depth_plan fuel target_ops target_op f target_len ps1` >>
  gvs[UNCURRY_DEF] >>
  rename1 `reduce_depth_plan _ _ _ _ _ _ = (r_ops, ps2)` >>
  `1 <= LENGTH ps.ps_stack` by
    (drule stack_get_unfixed_depth_bound >> simp[]) >>
  `x' <= 16 /\ x' < LENGTH ps.ps_stack` by
    metis_tac[select_spill_candidate_bound] >>
  qspecl_then [`x'`, `ps`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] do_spill_at_wf_len) >> simp[] >>
  strip_tac >>
  first_x_assum
    (qspecl_then [`target_ops`, `target_op`, `f`, `target_len`, `ps1`, `lo`]
      mp_tac) >>
  simp[LET_THM] >> strip_tac >>
  irule prefix_wf_len_append >> metis_tac[]
QED

(* ===== reorder_one: single reorder step ===== *)

(* ===== Stack length helpers for reorder_one ===== *)

(* do_swap preserves stack length *)
Theorem do_swap_length:
  !dist ps. dist < LENGTH ps.ps_stack ==>
    LENGTH (SND (do_swap dist ps)).ps_stack = LENGTH ps.ps_stack
Proof
  rpt strip_tac >>
  Cases_on `dist = 0`
  >- simp[do_swap_def]
  >>
  Cases_on `dist <= 16`
  >- simp[do_swap_def, stack_swap_length]
  >>
  (* Deep swap path *)
  simp[do_swap_def] >>
  qabbrev_tac `chunk = dist + 1` >>
  qabbrev_tac `items = top_n chunk ps.ps_stack` >>
  qabbrev_tac `fres = FOLDL
    (\(ops,offs,al) (item:operand).
      (\(off,al'). (ops ++ [SOSpill off], SNOC off offs, al'))
        (alloc_spill_slot al)) ([],[],ps.ps_alloc) items` >>
  PairCases_on `fres` >> simp[] >>
  simp[LENGTH_APPEND, LENGTH_MAP, LENGTH_REVERSE, LENGTH_GENLIST] >>
  `LENGTH items = chunk` by
    (simp[Abbr `items`, top_n_def, LENGTH_TAKE_EQ, LENGTH_REVERSE] >>
     simp[Abbr `chunk`]) >>
  simp[Abbr `chunk`] >>
  simp[LENGTH_TAKE_EQ, LENGTH_REVERSE]
QED

(* do_restore increases stack length by 0 or 1 *)
Theorem do_restore_length:
  !op ps.
    LENGTH (SND (do_restore op ps)).ps_stack <=
    LENGTH ps.ps_stack + 1 /\
    LENGTH ps.ps_stack <= LENGTH (SND (do_restore op ps)).ps_stack
Proof
  rpt gen_tac >>
  simp[do_restore_def] >>
  Cases_on `FLOOKUP ps.ps_spilled op` >>
  simp[stack_push_length]
QED

(* ===== stack_find / stack_get_depth after element removal ===== *)

(* Removing element at position k from a list shifts stack_find for
   a match at position d > k to position d-1 *)
Theorem stack_find_remove_at[local]:
  !xs p k d.
    stack_find p xs = SOME d /\ k < d /\ k < LENGTH xs /\ ~p (EL k xs) ==>
    stack_find p (TAKE k xs ++ DROP (SUC k) xs) = SOME (d - 1)
Proof
  Induct >> simp[stack_find_def] >>
  rpt gen_tac >> strip_tac >>
  Cases_on `k`
  >- (
    (* k = 0: remove first element *)
    gvs[] >>
    Cases_on `stack_find p xs` >> gvs[]
  )
  >>
  rename1 `SUC k' < d` >>
  Cases_on `p h`
  >- (
    (* p h = T: match at position 0. But d > SUC k' >= 1. Contradiction *)
    gvs[]
  )
  >>
  gvs[] >>
  Cases_on `stack_find p xs` >> gvs[] >>
  rename1 `stack_find p xs = SOME d1` >>
  simp[stack_find_def] >>
  first_x_assum (qspecl_then [`p`, `k'`, `d1`] mp_tac) >>
  simp[EL]
QED

(* do_spill_at_length: exact length change *)
Theorem do_spill_at_length_exact[local]:
  !cand ps. 1 <= LENGTH ps.ps_stack ==>
    LENGTH (SND (do_spill_at cand ps)).ps_stack = LENGTH ps.ps_stack - 1
Proof
  rpt strip_tac >> simp[do_spill_at_def] >>
  Cases_on `cand = 0`
  >- (simp[do_spill_tos_def, LET_THM] >>
      Cases_on `alloc_spill_slot ps.ps_alloc` >> simp[stack_pop_def])
  >> simp[LET_THM] >>
  Cases_on `do_spill_tos (ps with ps_stack := stack_swap cand ps.ps_stack)` >>
  simp[] >>
  fs[do_spill_tos_def, LET_THM] >>
  Cases_on `alloc_spill_slot
    (ps with ps_stack := stack_swap cand ps.ps_stack).ps_alloc` >>
  gvs[stack_pop_def, stack_swap_length, LENGTH_LUPDATE]
QED

(* select_spill_candidate returns value < target_dist *)
Theorem select_spill_candidate_lt_dist[local]:
  !stk forbidden target_dist target_len cand.
    1 <= target_dist ==>
    select_spill_candidate stk forbidden target_dist target_len = SOME cand ==>
    cand < target_dist
Proof
  rpt gen_tac >> rpt disch_tac >>
  fs[select_spill_candidate_def, LET_THM] >>
  imp_res_tac find_mem >>
  fs[MEM_GENLIST] >>
  qabbrev_tac `mx = MIN 16 (MIN (target_dist - 1) (LENGTH stk - 1))` >>
  `mx <= target_dist - 1` by
    (unabbrev_all_tac >> simp[MIN_DEF]) >>
  simp[]
QED

(* select_spill_candidate picks non-forbidden item *)
Theorem select_spill_candidate_not_forbidden[local]:
  !stk forbidden target_dist target_len cand.
    select_spill_candidate stk forbidden target_dist target_len = SOME cand ==>
    cand < LENGTH stk ==>
    ~MEM (stack_peek cand stk) forbidden
Proof
  rpt gen_tac >> rpt disch_tac >>
  fs[select_spill_candidate_def, LET_THM] >>
  imp_res_tac FIND_SOME_MEM >> gvs[]
QED

(* LUPDATE preserves stack_find when the update is at a position before the match
   and the new value doesn't match the predicate *)
Theorem stack_find_lupdate[local]:
  !xs p d i v.
    stack_find p xs = SOME d /\ i < d /\ i < LENGTH xs /\ ~p v ==>
    stack_find p (LUPDATE v i xs) = SOME d
Proof
  Induct >> simp[stack_find_def, LUPDATE_def] >>
  rpt gen_tac >>
  Cases_on `p h` >> simp[stack_find_def]
  >- (
    (* p h: d = 0, i < 0 contradiction *)
    rpt strip_tac >> gvs[]
  ) >>
  (* ~p h *)
  Cases_on `stack_find p xs` >> simp[] >>
  rename1 `stack_find p xs = SOME d1` >>
  rpt strip_tac >>
  Cases_on `i` >> simp[LUPDATE_def, stack_find_def] >>
  first_x_assum (qspecl_then [`p`, `d1`, `n`, `v`] mp_tac) >>
  simp[]
QED

(* REVERSE commutes with LUPDATE (index reflection) *)
Theorem reverse_lupdate[local]:
  !xs (v:'a) i. i < LENGTH xs ==>
    REVERSE (LUPDATE v i xs) =
    LUPDATE v (LENGTH xs - 1 - i) (REVERSE xs)
Proof
  Induct >> simp[LUPDATE_def] >>
  rpt gen_tac >> strip_tac >>
  Cases_on `i` >> simp[LUPDATE_def, REVERSE_DEF, SNOC_APPEND]
  >- (
    `LENGTH (REVERSE xs) <= LENGTH xs` by simp[] >>
    simp[LUPDATE_APPEND2, LENGTH_REVERSE, LUPDATE_def]
  )
  >>
  rename1 `SUC n < SUC (LENGTH xs)` >>
  `n < LENGTH xs` by simp[] >>
  first_x_assum (qspecl_then [`v`, `n`] mp_tac) >>
  simp[] >> strip_tac >>
  simp[REVERSE_DEF, SNOC_APPEND] >>
  `LENGTH xs - 1 - n < LENGTH (REVERSE xs)` by simp[] >>
  simp[LUPDATE_APPEND1] >>
  `LENGTH xs - SUC n = LENGTH xs - 1 - n` by simp[] >>
  simp[]
QED

(* Helper: stack_find returns NONE at positions before match *)
Theorem stack_find_no_earlier_match[local]:
  !xs p d. stack_find p xs = SOME d ==>
    !i. i < d ==> i < LENGTH xs ==> ~p (EL i xs)
Proof
  Induct >> simp[stack_find_def] >>
  rpt gen_tac >> strip_tac >>
  Cases_on `p h` >> gvs[] >>
  (* ~p h: case on stack_find result *)
  Cases_on `stack_find p xs` >> gvs[] >>
  rename1 `stack_find p xs = SOME d1` >>
  rpt strip_tac >>
  Cases_on `i` >> gvs[EL] >>
  first_x_assum irule >> simp[]
QED

(* LUPDATE at different indices commutes *)
Theorem lupdate_commutes[local]:
  !i j (a:'a) b xs.
    i <> j ==>
    LUPDATE a i (LUPDATE b j xs) = LUPDATE b j (LUPDATE a i xs)
Proof
  Induct_on `xs` >> simp[LUPDATE_def] >>
  rpt gen_tac >> strip_tac >>
  Cases_on `i` >> Cases_on `j` >> gvs[LUPDATE_def]
QED

(* REVERSE of stack_swap expressed purely in REVERSE stk terms *)
Theorem reverse_stack_swap[local]:
  !cand stk. cand < LENGTH stk /\ 0 < LENGTH stk ==>
    REVERSE (stack_swap cand stk) =
    LUPDATE (EL cand (REVERSE stk)) 0
      (LUPDATE (EL 0 (REVERSE stk)) cand (REVERSE stk))
Proof
  rpt strip_tac >>
  simp[stack_swap_def, LET_THM] >>
  `LENGTH stk - 1 < LENGTH stk` by simp[] >>
  `LENGTH stk - 1 - cand < LENGTH stk` by simp[] >>
  simp[reverse_lupdate, LENGTH_LUPDATE] >>
  `EL (LENGTH stk - 1) stk = EL 0 (REVERSE stk)` by
    simp[Once EL_REVERSE, PRE_SUB1] >>
  `EL (LENGTH stk - 1 - cand) stk = EL cand (REVERSE stk)` by
    (`LENGTH stk - 1 - cand = PRE (LENGTH stk - cand)` by simp[] >>
     pop_assum SUBST1_TAC >> simp[Once EL_REVERSE]) >>
  `LENGTH stk - (cand + 1) = LENGTH stk - 1 - cand` by simp[] >>
  `HD (REVERSE stk) = EL 0 (REVERSE stk)` by simp[EL] >>
  ntac 4 (pop_assum (fn th => CONV_TAC (DEPTH_CONV (REWR_CONV th)))) >>
  Cases_on `cand = 0` >> simp[] >>
  simp[Once lupdate_commutes]
QED

(* stack_swap preserves stack_get_depth for items deeper than cand *)
Theorem stack_swap_get_depth_deep[local]:
  !cand stk op d.
    stack_get_depth op stk = SOME d /\
    cand < d /\ cand < LENGTH stk ==>
    stack_get_depth op (stack_swap cand stk) = SOME d
Proof
  rpt strip_tac >>
  imp_res_tac stack_get_depth_bound >>
  `0 < LENGTH stk` by simp[] >>
  simp[stack_get_depth_def, reverse_stack_swap] >>
  fs[stack_get_depth_def] >>
  (* Positions 0 and cand don't match op *)
  `~((\x. x = op) (EL 0 (REVERSE stk)))` by
    (drule stack_find_no_earlier_match >>
     disch_then (qspec_then `0` mp_tac) >> simp[LENGTH_REVERSE]) >>
  `~((\x. x = op) (EL cand (REVERSE stk)))` by
    (drule stack_find_no_earlier_match >>
     disch_then (qspec_then `cand` mp_tac) >> simp[LENGTH_REVERSE]) >>
  (* Inner LUPDATE at cand *)
  `stack_find (\x. x = op)
     (LUPDATE (EL 0 (REVERSE stk)) cand (REVERSE stk)) = SOME d` by
    (irule stack_find_lupdate >> simp[LENGTH_REVERSE]) >>
  (* Outer LUPDATE at 0 *)
  `HD (REVERSE stk) = EL 0 (REVERSE stk)` by simp[EL] >>
  pop_assum (fn th => fs[GSYM th]) >>
  irule stack_find_lupdate >>
  simp[LENGTH_LUPDATE, LENGTH_REVERSE]
QED

(* stack_pop 1 decreases stack_get_depth by 1 when TOS doesn't match *)
Theorem stack_pop_get_depth[local]:
  !stk op d.
    stack_get_depth op stk = SOME d /\ d > 0 ==>
    stack_get_depth op (stack_pop 1 stk) = SOME (d - 1)
Proof
  rpt strip_tac >>
  imp_res_tac stack_get_depth_bound >>
  simp[stack_get_depth_def, stack_pop_def] >>
  (* REVERSE (TAKE (LENGTH stk - 1) stk) = TL (REVERSE stk) *)
  `stk <> []` by (Cases_on `stk` >> fs[]) >>
  `TAKE (LENGTH stk - 1) stk = FRONT stk` by simp[GSYM FRONT_BY_TAKE] >>
  `REVERSE (FRONT stk) = TL (REVERSE stk)` by simp[GSYM REVERSE_TL] >>
  simp[] >>
  fs[stack_get_depth_def] >>
  `REVERSE stk <> []` by simp[REVERSE_EQ_NIL] >>
  Cases_on `REVERSE stk` >> gvs[] >>
  simp[stack_find_def] >>
  Cases_on `h = op`
  >- gvs[stack_find_def] >>
  fs[stack_find_def] >>
  Cases_on `stack_find (\x. x = op) (REVERSE (FRONT stk))` >> gvs[]
QED

(* Key: stack_get_depth after do_spill_at decreases by 1 for items deeper
   than the spill candidate, when the candidate does not match *)
Theorem do_spill_at_get_depth[local]:
  !cand ps op d.
    stack_get_depth op ps.ps_stack = SOME d /\
    cand < d /\ cand < LENGTH ps.ps_stack /\
    stack_peek cand ps.ps_stack <> op ==>
    stack_get_depth op (SND (do_spill_at cand ps)).ps_stack = SOME (d - 1)
Proof
  rpt strip_tac >>
  imp_res_tac stack_get_depth_bound >>
  Cases_on `cand = 0`
  >- (
    (* cand = 0: do_spill_at 0 = do_spill_tos = pop TOS *)
    simp[do_spill_at_def, do_spill_tos_def, LET_THM] >>
    Cases_on `alloc_spill_slot ps.ps_alloc` >> simp[] >>
    irule stack_pop_get_depth >> simp[]
  )
  >>
  (* cand > 0: swap cand to TOS, then pop *)
  simp[do_spill_at_def, LET_THM] >>
  Cases_on `do_spill_tos (ps with ps_stack := stack_swap cand ps.ps_stack)` >>
  simp[] >> rename1 `do_spill_tos _ = (sp_ops, ps1)` >>
  (* ps1.ps_stack = stack_pop 1 (stack_swap cand ps.ps_stack) *)
  `ps1.ps_stack = stack_pop 1 (stack_swap cand ps.ps_stack)` by
    (fs[do_spill_tos_def, LET_THM] >>
     Cases_on `alloc_spill_slot
       (ps with ps_stack := stack_swap cand ps.ps_stack).ps_alloc` >>
     gvs[]) >>
  simp[] >>
  (* Step 1: swap preserves depth d *)
  `stack_get_depth op (stack_swap cand ps.ps_stack) = SOME d` by
    (irule stack_swap_get_depth_deep >> simp[]) >>
  (* Step 2: pop decreases depth to d-1 *)
  irule stack_pop_get_depth >> simp[]
QED

(* When the selected unfixed depth is at most 16, reduction is identity. *)
Theorem reduce_depth_plan_le_16:
  !fuel target_ops target_op f target_len ps d.
    stack_get_unfixed_depth target_op f target_len ps.ps_stack = SOME d /\
    d <= 16 ==>
    reduce_depth_plan fuel target_ops target_op f target_len ps = ([], ps)
Proof
  Cases_on `fuel` >> simp[reduce_depth_plan_def]
QED

(* do_restore puts op at depth 0 *)
Theorem do_restore_get_depth_zero[local]:
  !op ps off.
    FLOOKUP ps.ps_spilled op = SOME off ==>
    stack_get_depth op (SND (do_restore op ps)).ps_stack = SOME 0
Proof
  rpt strip_tac >>
  simp[do_restore_def, stack_get_depth_def, stack_push_def,
       listTheory.REVERSE_SNOC, stack_find_def]
QED

Theorem reduce_depth_plan_protected_identity:
  !fuel target_ops target_op f target_len ps.
    f + 1 < target_len ==>
    reduce_depth_plan fuel target_ops target_op f target_len ps = ([],ps)
Proof
  Cases >> simp[reduce_depth_plan_def]
QED

(* Reduction preserves a deep unfixed occurrence; safe candidates lie below
   the finalized target window and cannot remove the selected operand. *)
Theorem reduce_depth_plan_dist_ge:
  !fuel target_ops target_op f target_len ps d.
    MEM target_op target_ops /\
    stack_get_unfixed_depth target_op f target_len ps.ps_stack = SOME d /\
    d > 16 ==>
    let (_, ps') =
      reduce_depth_plan fuel target_ops target_op f target_len ps in
    ?d'. stack_get_unfixed_depth target_op f target_len ps'.ps_stack = SOME d' /\
         16 <= d'
Proof
  Induct
  >- (rpt strip_tac >> simp[reduce_depth_plan_def] >>
      qexists `d` >> simp[]) >>
  rpt gen_tac >> strip_tac >>
  Cases_on `f + 1 < target_len`
  >- (simp[reduce_depth_plan_def] >> qexists `d` >> simp[]) >>
  `target_len <= f + 1` by decide_tac >>
  `stack_get_depth target_op ps.ps_stack = SOME d` by
    metis_tac[stack_get_unfixed_depth_empty_window] >>
  simp[reduce_depth_plan_def] >>
  Cases_on `select_spill_candidate ps.ps_stack target_ops d target_len`
  >- (simp[] >> qexists `d` >> simp[]) >>
  `1 <= LENGTH ps.ps_stack` by
    metis_tac[stack_get_depth_nonempty] >>
  `x < d` by
    (qspecl_then [`ps.ps_stack`, `target_ops`, `d`, `target_len`, `x`]
       mp_tac select_spill_candidate_lt_dist >> simp[]) >>
  `x <= 16 /\ x < LENGTH ps.ps_stack` by
    metis_tac[select_spill_candidate_bound] >>
  `stack_peek x ps.ps_stack <> target_op` by
    metis_tac[select_spill_candidate_not_forbidden] >>
  `stack_get_depth target_op (SND (do_spill_at x ps)).ps_stack =
     SOME (d - 1)` by
    metis_tac[do_spill_at_get_depth] >>
  `stack_get_unfixed_depth target_op f target_len
     (SND (do_spill_at x ps)).ps_stack = SOME (d - 1)` by
    metis_tac[stack_get_unfixed_depth_empty_window] >>
  Cases_on `do_spill_at x ps` >>
  rename1 `do_spill_at x ps = (spill_ops, ps1)` >>
  gvs[] >>
  Cases_on `d - 1 = 16`
  >- (`reduce_depth_plan fuel target_ops target_op f target_len ps1 =
         ([], ps1)` by
        (irule reduce_depth_plan_le_16 >> simp[]) >>
      simp[] >> qexists `16` >> simp[]) >>
  `d - 1 > 16` by decide_tac >>
  first_x_assum
    (qspecl_then [`target_ops`, `target_op`, `f`, `target_len`, `ps1`, `d - 1`]
      mp_tac) >>
  Cases_on `reduce_depth_plan fuel target_ops target_op f target_len ps1` >>
  simp[]
QED

(* stack_poke preserves length *)
Theorem stack_poke_length[local]:
  !dist v stk. LENGTH (stack_poke dist v stk) = LENGTH stk
Proof
  rpt gen_tac >> simp[stack_poke_def, LENGTH_LUPDATE]
QED

(* reorder_one_wf_len: preconditions are necessary.
   - Without preconditions the statement is FALSE: do_swap final_dist
     can be called with final_dist >= LENGTH ps.ps_stack.
   - target_idx < LENGTH target_ops /\ LENGTH target_ops <= LENGTH ps.ps_stack
     ensures final_dist < LENGTH target_ops <= LENGTH ps.ps_stack.
   - reduce_depth_plan preserves at least LENGTH target_ops items
     because select_spill_candidate avoids target_ops items.
   - LENGTH target_ops <= 16 is required: without it, when
     LENGTH target_ops = LENGTH ps.ps_stack = 18 and target_idx = 0,
     reduce_depth_plan spills 1 item (stack 17), then do_swap 17 on
     a 17-item stack fails. With the bound, dist' <= 16 and
     LENGTH ps2.ps_stack >= 17. This matches the EVM DUP/SWAP depth
     limit of 16. *)
(* Helper: two do_swaps are prefix_wf when both distances < stack length *)
Theorem two_swaps_wf[local]:
  !d1 d2 ps2 lo.
    d1 < LENGTH ps2.ps_stack /\
    d2 < LENGTH ps2.ps_stack ==>
    let (s1, ps3) = do_swap d1 ps2 in
    let (s2, ps4) = do_swap d2 ps3 in
      prefix_wf lo (LENGTH ps2.ps_stack) (s1 ++ s2) /\
      prefix_end_len lo (LENGTH ps2.ps_stack) (s1 ++ s2) =
        LENGTH ps4.ps_stack
Proof
  rpt strip_tac >>
  Cases_on `do_swap d1 ps2` >>
  rename1 `do_swap d1 ps2 = (s1, ps3)` >> simp[] >>
  Cases_on `do_swap d2 ps3` >>
  rename1 `_ = (s2, ps4)` >> simp[] >>
  qspecl_then [`d1`, `ps2`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] do_swap_wf_len) >> simp[] >>
  strip_tac >>
  `LENGTH ps3.ps_stack = LENGTH ps2.ps_stack` by
    (qspecl_then [`d1`, `ps2`] mp_tac do_swap_length >> simp[]) >>
  `d2 < LENGTH ps3.ps_stack` by simp[] >>
  qspecl_then [`d2`, `ps3`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] do_swap_wf_len) >> simp[] >>
  strip_tac >>
  irule prefix_wf_len_append >> metis_tac[]
QED

(*  Place phase helper: handles the final positioning of an operand.
    After restore+reduce, we have op at depth dist' in ps2.
    Place it at final_dist. 4 sub-cases in reorder_one_def. *)
Theorem place_phase_wf_len[local]:
  !dfg op dist' final_dist ps2 lo n.
    dist' < LENGTH ps2.ps_stack /\
    final_dist < LENGTH ps2.ps_stack /\
    n = LENGTH ps2.ps_stack ==>
    let (place_ops, ps_out) =
      if dist' = final_dist then ([] : stack_op list, ps2)
      else if final_dist < LENGTH ps2.ps_stack then
        let at_target = stack_peek final_dist ps2.ps_stack in
        if operand_equiv dfg op at_target then
          ([] : stack_op list,
           ps2 with ps_stack :=
             stack_poke final_dist op
               (stack_poke dist' at_target ps2.ps_stack))
        else
          let (s1, ps3) = do_swap dist' ps2 in
          let (s2, ps4) = do_swap final_dist ps3 in
          (s1 ++ s2, ps4)
      else
        let (s1, ps3) = do_swap dist' ps2 in
        let (s2, ps4) = do_swap final_dist ps3 in
        (s1 ++ s2, ps4)
    in
      prefix_wf lo n place_ops /\
      prefix_end_len lo n place_ops = LENGTH ps_out.ps_stack
Proof
  rpt strip_tac >> simp[LET_THM] >>
  IF_CASES_TAC >- simp[prefix_wf_def, prefix_end_len_def] >>
  (* dist' <> final_dist *)
  (* final_dist < LENGTH ps2.ps_stack is TRUE by hypothesis *)
  `final_dist < LENGTH ps2.ps_stack` by simp[] >>
  simp[] >>
  IF_CASES_TAC
  >- (
    (* operand_equiv: two pokes, no ops *)
    simp[stack_poke_length]
  ) >>
  (* two swaps *)
  qspecl_then [`dist'`, `final_dist`, `ps2`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] two_swaps_wf) >>
  simp[] >> pairarg_tac >> simp[] >> pairarg_tac >> simp[]
QED

Theorem reorder_one_wf_len:
  !dfg target_ops target_idx op ps lo.
    target_idx < LENGTH target_ops /\
    LENGTH target_ops <= LENGTH ps.ps_stack /\
    LENGTH target_ops <= 16 /\
    MEM op target_ops ==>
    let (ops, ps') = reorder_one dfg target_ops target_idx op ps in
    prefix_wf lo (LENGTH ps.ps_stack) ops /\
    prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack /\
    LENGTH target_ops <= LENGTH ps'.ps_stack
Proof
  rpt strip_tac >>
  simp[reorder_one_def, LET_THM] >>
  Cases_on `stack_get_unfixed_depth op
    (LENGTH target_ops - (target_idx + 1)) (LENGTH target_ops) ps.ps_stack`
  >- (
    simp[] >>
    Cases_on `FLOOKUP ps.ps_spilled op`
    >- simp[prefix_wf_def, prefix_end_len_def] >>
    simp[] >>
    Cases_on `do_restore op ps` >>
    rename1 `do_restore op ps = (restore_ops, ps1)` >> simp[] >>
    `stack_get_depth op ps1.ps_stack = SOME 0` by
      (qspecl_then [`op`, `ps`, `x`] mp_tac do_restore_get_depth_zero >>
       simp[]) >>
    `stack_get_unfixed_depth op
       (LENGTH target_ops - (target_idx + 1)) (LENGTH target_ops)
       ps1.ps_stack = SOME 0` by
      metis_tac[stack_get_unfixed_depth_zero] >>
    simp[] >>
    suspend "none_restore"
  ) >>
  rename1 `stack_get_unfixed_depth op _ _ ps.ps_stack = SOME d` >>
  simp[] >>
  drule stack_get_unfixed_depth_bound >> strip_tac >>
  IF_CASES_TAC
  >- (
    simp[] >>
    Cases_on `reduce_depth_plan (LENGTH ps.ps_stack) target_ops op
      (LENGTH target_ops - (target_idx + 1)) (LENGTH target_ops) ps` >>
    rename1 `reduce_depth_plan _ _ _ _ _ _ = (reduce_ops, ps2)` >>
    simp[] >>
    qspecl_then [`LENGTH ps.ps_stack`, `target_ops`, `op`,
      `LENGTH target_ops - (target_idx + 1)`, `LENGTH target_ops`, `ps`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] reduce_depth_plan_wf_len) >>
    simp[] >> strip_tac >>
    `?d'. stack_get_unfixed_depth op
             (LENGTH target_ops - (target_idx + 1)) (LENGTH target_ops)
             ps2.ps_stack = SOME d' /\ 16 <= d'` by
      (qspecl_then [`LENGTH ps.ps_stack`, `target_ops`, `op`,
         `LENGTH target_ops - (target_idx + 1)`, `LENGTH target_ops`,
         `ps`, `d`]
         mp_tac (REWRITE_RULE [LET_THM] reduce_depth_plan_dist_ge) >>
       simp[]) >>
    simp[] >>
    suspend "some_deep"
  ) >>
  simp[] >>
  suspend "some_shallow"
QED

Resume reorder_one_wf_len[none_restore]:
  (* do_restore wf/len *)
  `prefix_wf lo (LENGTH ps.ps_stack) restore_ops /\
   prefix_end_len lo (LENGTH ps.ps_stack) restore_ops =
     LENGTH ps1.ps_stack` by
    (qspecl_then [`op`, `ps`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] do_restore_wf_len) >> simp[]) >>
  `LENGTH ps.ps_stack <= LENGTH ps1.ps_stack` by
    (`ps1 = SND (do_restore op ps)` by simp[] >>
     pop_assum SUBST1_TAC >>
     mp_tac (Q.SPECL [`op`, `ps`] do_restore_length) >> simp[]) >>
  (* Case 1: final_dist = 0 *)
  IF_CASES_TAC >- (simp[] >> decide_tac) >>
  (* Case 2: final_dist < LENGTH ps1.ps_stack (always true) *)
  `LENGTH target_ops < target_idx + (LENGTH ps1.ps_stack + 1)` by
    decide_tac >>
  `0 < target_idx + LENGTH ps1.ps_stack` by decide_tac >>
  `0 < LENGTH ps1.ps_stack` by decide_tac >>
  simp[] >>
  IF_CASES_TAC
  >- (
    (* operand_equiv: two pokes, no extra ops *)
    simp[stack_poke_length] >> decide_tac
  ) >>
  (* two swaps *)
  `LENGTH target_ops - (target_idx + 1) < LENGTH ps1.ps_stack` by
    decide_tac >>
  qspecl_then [`0`,
    `LENGTH target_ops - (target_idx + 1)`, `ps1`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] two_swaps_wf) >>
  simp[] >> pairarg_tac >> simp[] >> pairarg_tac >> simp[] >>
  strip_tac >>
  `LENGTH (SND (do_swap 0 ps1)).ps_stack = LENGTH ps1.ps_stack` by
    (qspecl_then [`0`, `ps1`] mp_tac do_swap_length >> simp[]) >>
  `LENGTH (SND (do_swap (LENGTH target_ops - (target_idx + 1))
    (SND (do_swap 0 ps1)))).ps_stack = LENGTH ps1.ps_stack` by
    (qspecl_then [`LENGTH target_ops - (target_idx + 1)`,
       `SND (do_swap 0 ps1)`] mp_tac do_swap_length >>
     simp[] >> decide_tac) >>
  conj_tac
  >- (once_rewrite_tac [GSYM APPEND_ASSOC] >>
      metis_tac[prefix_wf_len_append]) >>
  conj_tac
  >- (once_rewrite_tac [GSYM APPEND_ASSOC] >>
      metis_tac[prefix_wf_len_append]) >>
  gvs[]
QED

Resume reorder_one_wf_len[some_deep]:
  drule stack_get_unfixed_depth_bound >> strip_tac >>
  `LENGTH target_ops < target_idx + (LENGTH ps2.ps_stack + 1) /\
   0 < target_idx + LENGTH ps2.ps_stack /\
   0 < LENGTH ps2.ps_stack` by decide_tac >>
  simp[] >>
  IF_CASES_TAC
  >- (
    (* operand_equiv: poke only, ops = reduce_ops *)
    simp[stack_poke_length] >> decide_tac
  ) >>
  (* two swaps *)
  `d' < LENGTH ps2.ps_stack` by decide_tac >>
  `LENGTH target_ops - (target_idx + 1) < LENGTH ps2.ps_stack` by
    decide_tac >>
  qspecl_then [`d'`,
    `LENGTH target_ops - (target_idx + 1)`, `ps2`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] two_swaps_wf) >>
  simp[] >> pairarg_tac >> simp[] >> pairarg_tac >> simp[] >>
  strip_tac >>
  `LENGTH (SND (do_swap d' ps2)).ps_stack = LENGTH ps2.ps_stack` by
    (qspecl_then [`d'`, `ps2`] mp_tac do_swap_length >> simp[]) >>
  `LENGTH (SND (do_swap (LENGTH target_ops - (target_idx + 1))
    (SND (do_swap d' ps2)))).ps_stack = LENGTH ps2.ps_stack` by
    (qspecl_then [`LENGTH target_ops - (target_idx + 1)`,
       `SND (do_swap d' ps2)`] mp_tac do_swap_length >>
     simp[] >> decide_tac) >>
  conj_tac
  >- (once_rewrite_tac [GSYM APPEND_ASSOC] >>
      metis_tac[prefix_wf_len_append]) >>
  conj_tac
  >- (once_rewrite_tac [GSYM APPEND_ASSOC] >>
      metis_tac[prefix_wf_len_append]) >>
  gvs[]
QED

Resume reorder_one_wf_len[some_shallow]:
  IF_CASES_TAC >- simp[prefix_wf_def, prefix_end_len_def] >>
  `LENGTH target_ops - (target_idx + 1) < LENGTH ps.ps_stack` by
    decide_tac >>
  simp[] >>
  IF_CASES_TAC
  >- (simp[stack_poke_length]) >>
  qspecl_then [`d`,
    `LENGTH target_ops - (target_idx + 1)`, `ps`, `lo`]
    mp_tac (REWRITE_RULE [LET_THM] two_swaps_wf) >>
  simp[] >> pairarg_tac >> simp[] >> pairarg_tac >> simp[] >>
  strip_tac >>
  `LENGTH (SND (do_swap d ps)).ps_stack = LENGTH ps.ps_stack` by
    (qspecl_then [`d`, `ps`] mp_tac do_swap_length >> simp[]) >>
  `LENGTH (SND (do_swap (LENGTH target_ops - (target_idx + 1))
    (SND (do_swap d ps)))).ps_stack = LENGTH ps.ps_stack` by
    (qspecl_then [`LENGTH target_ops - (target_idx + 1)`,
       `SND (do_swap d ps)`] mp_tac do_swap_length >>
     simp[] >> decide_tac) >>
  gvs[]
QED

Finalise reorder_one_wf_len;

(* ===== reorder_plan: FOLDL of reorder_one ===== *)

Theorem reorder_plan_foldl_wf_len[local]:
  !items dfg target_ops acc_ops ps lo n.
    LENGTH target_ops <= 16 /\
    LENGTH target_ops <= LENGTH ps.ps_stack /\
    prefix_wf lo n acc_ops /\
    prefix_end_len lo n acc_ops = LENGTH ps.ps_stack /\
    EVERY (\(idx, op). idx < LENGTH target_ops /\ MEM op target_ops) items
    ==>
    let (result_ops, ps') =
      FOLDL (\(ops,ps) (idx,op).
        let (step_ops,ps') = reorder_one dfg target_ops idx op ps in
          (ops ++ step_ops, ps'))
        (acc_ops, ps) items in
    prefix_wf lo n result_ops /\
    prefix_end_len lo n result_ops = LENGTH ps'.ps_stack /\
    LENGTH target_ops <= LENGTH ps'.ps_stack
Proof
  Induct >> simp[LET_THM] >>
  Cases >> rename1 `(idx, op)` >>
  rpt gen_tac >> rpt disch_tac >>
  simp[FOLDL, LET_THM] >>
  Cases_on `reorder_one dfg target_ops idx op ps` >>
  gvs[UNCURRY_DEF] >>
  rename1 `reorder_one _ _ _ _ _ = (step_ops, ps1)` >>
  (* Get wf/len/stack from reorder_one_wf_len *)
  `prefix_wf lo (LENGTH ps.ps_stack) step_ops /\
   prefix_end_len lo (LENGTH ps.ps_stack) step_ops = LENGTH ps1.ps_stack /\
   LENGTH target_ops <= LENGTH ps1.ps_stack` by
    (qspecl_then [`dfg`, `target_ops`, `idx`, `op`, `ps`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] reorder_one_wf_len) >>
     simp[]) >>
  (* Compose *)
  `prefix_wf lo n (acc_ops ++ step_ops) /\
   prefix_end_len lo n (acc_ops ++ step_ops) = LENGTH ps1.ps_stack` by
    metis_tac[prefix_wf_append, prefix_end_len_append] >>
  (* Apply IH *)
  first_x_assum
    (qspecl_then [`dfg`, `target_ops`, `acc_ops ++ step_ops`, `ps1`,
                  `lo`, `n`] mp_tac) >>
  simp[LET_THM]
QED

Theorem reorder_plan_wf_len:
  !dfg target_ops ps lo.
    LENGTH target_ops <= LENGTH ps.ps_stack /\
    LENGTH target_ops <= 16 ==>
    let (ops, ps') = reorder_plan dfg target_ops ps in
    prefix_wf lo (LENGTH ps.ps_stack) ops /\
    prefix_end_len lo (LENGTH ps.ps_stack) ops = LENGTH ps'.ps_stack
Proof
  rpt gen_tac >> rpt disch_tac >>
  simp[reorder_plan_def, LET_THM] >>
  `EVERY (\(idx:num, op:operand). idx < LENGTH target_ops /\ MEM op target_ops)
     (MAPi (\i op. (i, op)) target_ops)` by (
    simp[EVERY_MEM, FORALL_PROD, indexedListsTheory.MEM_MAPi] >>
    rpt strip_tac >> gvs[] >> metis_tac[MEM_EL]
  ) >>
  qspecl_then [`MAPi (\i (op:operand). (i, op)) target_ops`,
    `dfg`, `target_ops`, `([] : stack_op list)`, `ps`, `lo`,
    `LENGTH ps.ps_stack`]
    mp_tac (REWRITE_RULE [LET_THM] reorder_plan_foldl_wf_len) >>
  simp[prefix_wf_def, prefix_end_len_def] >>
  strip_tac >>
  Cases_on `FOLDL (\(ops,ps) (idx,op).
    (\(step_ops,ps'). (ops ++ step_ops, ps'))
      (reorder_one dfg target_ops idx op ps)) ([],ps)
    (MAPi (\i op. (i, op)) target_ops)` >>
  gvs[]
QED

(* When generate_regular_inst_plan produces prefix ++ [SOEmit name],
   the prefix is well-formed w.r.t. prefix_wf.
   This is the key bridge from code generation to prefix_sim.
   Depends on emit_input_plan_wf_len and reorder_plan_wf_len.
   NOTE: Internal proof will need inst.inst_opcode <> INVOKE and label FLOOKUP,
   but these should be derivable from generate_regular_inst_plan's structure
   (it's only called for non-INVOKE opcodes in generate_inst_plan). *)

Theorem generate_emit_ops_some[local,simp]:
  !inst ltc ps name.
    venom_to_evm_name inst.inst_opcode = SOME name ==>
    generate_emit_ops inst ltc ps = ([SOEmit name], ps)
Proof
  rpt strip_tac >>
  Cases_on `inst.inst_opcode = INITIAL_FMP` >> gvs[venom_to_evm_name_def] >>
  Cases_on `inst.inst_opcode = BUMP` >> gvs[venom_to_evm_name_def] >>
  simp[generate_emit_ops_def, LET_THM]
QED

(* regular_plan_prefix_wf_gen below supersedes the old regular_plan_prefix_wf.
   It proves both prefix_wf and EVERY is_prefix_op for the general
   prefix ++ [SOEmit name] ++ postfix decomposition. *)

(* If A ++ [e] ++ B = C ++ [e] ++ D where e is non-prefix and A,B are
   all prefix ops, the split is unique: C = A, D = B. *)
Theorem append_mid_split_unique[local]:
  !A (e:stack_op) B C D.
    EVERY is_prefix_op A /\ EVERY is_prefix_op B /\ ~is_prefix_op e /\
    A ++ [e] ++ B = C ++ [e] ++ D ==>
    C = A /\ D = B
Proof
  rpt strip_tac >> (
  qpat_x_assum `_ = _` mp_tac >>
  rewrite_tac[GSYM APPEND_ASSOC] >>
  simp[APPEND_EQ_APPEND] >> strip_tac >> gvs[] >>
  Cases_on `l` >> gvs[])
QED


(* When compute_operands returns [] and opcode is not JMP,
   the entire plan for a no-output instruction is just [SOEmit name] *)
Theorem regular_plan_empty_prefix:
  !liveness dfg cfg fn inst next_liveness is_halting
   next_is_term bb_label ps name.
    venom_to_evm_name inst.inst_opcode = SOME name /\
    inst.inst_outputs = [] /\
    compute_operands inst = [] /\
    inst.inst_opcode <> JMP ==>
    ?ps_out.
      generate_regular_inst_plan liveness dfg cfg fn inst
        next_liveness is_halting next_is_term bb_label ps =
      ([SOEmit name], ps_out)
Proof
  rpt strip_tac >>
  Cases_on `inst.inst_opcode = INITIAL_FMP` >> gvs[venom_to_evm_name_def] >>
  Cases_on `inst.inst_opcode = BUMP` >> gvs[venom_to_evm_name_def] >>
  simp[generate_regular_inst_plan_def] >>
  simp[emit_input_plan_nil] >>
  simp[] >>
  simp[] >>
  simp[reorder_plan_nil] >>
  simp[stack_pop_def] >>
  simp[generate_emit_ops_def] >>
  simp[]
QED


(* ===== is_prefix_op for generated ops ===== *)

(* Helper: the spill FOLDL in do_swap always produces prefix ops *)
Theorem spill_foldl_prefix_op[local]:
  !items acc_ops acc_offs acc_al ops offs al.
    FOLDL (\(ops,offs,al) item.
      let (off,al') = alloc_spill_slot al in
      (ops ++ [SOSpill off], SNOC off offs, al'))
    (acc_ops, acc_offs, acc_al) items = (ops, offs, al) /\
    EVERY is_prefix_op acc_ops ==>
    EVERY is_prefix_op ops
Proof
  Induct >> simp[FOLDL, LET_THM] >>
  rpt gen_tac >> pairarg_tac >> simp[] >>
  strip_tac >>
  first_x_assum (qspecl_then [`acc_ops ++ [SOSpill off]`,
    `SNOC off acc_offs`, `al'`, `ops`, `offs`, `al`] mp_tac) >>
  simp[EVERY_APPEND, is_prefix_op_def, LET_THM]
QED

(* do_swap always produces prefix ops *)
Theorem do_swap_prefix_op:
  !dist ps ops ps'.
    do_swap dist ps = (ops, ps') ==>
    EVERY is_prefix_op ops
Proof
  rpt gen_tac >>
  simp[Once do_swap_def] >>
  IF_CASES_TAC >> simp[] >>
  IF_CASES_TAC
  >- (strip_tac >> gvs[is_prefix_op_def]) >>
  simp[LET_THM] >> pairarg_tac >> simp[] >>
  strip_tac >> gvs[EVERY_APPEND, EVERY_MAP, is_prefix_op_def] >>
  qspecl_then [`top_n (dist + 1) ps.ps_stack`,
    `[]`, `[]`, `ps.ps_alloc`,
    `spill_ops`, `offsets`, `alloc'`] mp_tac spill_foldl_prefix_op >>
  simp[LET_THM]
QED

(* Helper: the FOLDL inside popmany_individual preserves EVERY is_prefix_op *)
Theorem popmany_foldl_prefix_op[local]:
  !sorted acc_ops ps0 ops ps'.
    FOLDL (\(ops,ps) v.
      case stack_get_depth v ps.ps_stack of
        NONE => (ops,ps)
      | SOME dist =>
        let (swap_ops,ps') = if dist = 0 then ([],ps) else do_swap dist ps in
        (ops ++ swap_ops ++ [SOPop 1],
         ps' with ps_stack := stack_pop 1 ps'.ps_stack))
    (acc_ops, ps0) sorted = (ops, ps') /\
    EVERY is_prefix_op acc_ops ==>
    EVERY is_prefix_op ops
Proof
  Induct >> simp[FOLDL] >>
  rpt gen_tac >>
  Cases_on `stack_get_depth h ps0.ps_stack` >> simp[]
  >- (strip_tac >> gvs[] >> first_x_assum irule >> metis_tac[]) >>
  Cases_on `x = 0` >> simp[]
  >- (strip_tac >> gvs[] >>
      first_x_assum (qspecl_then [`acc_ops ++ [SOPop 1]`,
        `ps0 with ps_stack := stack_pop 1 ps0.ps_stack`,
        `ops`, `ps'`] mp_tac) >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
  pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
  first_x_assum (qspecl_then [
    `acc_ops ++ swap_ops ++ [SOPop 1]`,
    `ps'' with ps_stack := stack_pop 1 ps''.ps_stack`,
    `ops`, `ps'`] mp_tac) >>
  imp_res_tac do_swap_prefix_op >>
  simp[EVERY_APPEND, is_prefix_op_def]
QED

(* popmany_individual produces prefix ops — uses the FOLDL lemma *)
Theorem popmany_individual_prefix_op[local]:
  !to_pop ps ops ps'.
    popmany_individual to_pop ps = (ops, ps') ==>
    EVERY is_prefix_op ops
Proof
  rpt gen_tac >> simp[popmany_individual_def] >>
  qmatch_goalsub_abbrev_tac `FOLDL _ _ sorted` >>
  strip_tac >>
  qspecl_then [`sorted`, `[]`, `ps`, `ops`, `ps'`]
    mp_tac popmany_foldl_prefix_op >>
  simp[LET_THM, Abbr `sorted`]
QED

(* popmany_plan produces prefix ops *)
Theorem popmany_plan_prefix_op:
  !to_pop ps ops ps'.
    popmany_plan to_pop ps = (ops, ps') ==>
    EVERY is_prefix_op ops
Proof
  Cases >> rpt gen_tac >> simp[popmany_plan_def] >>
  IF_CASES_TAC >> simp[]
  >- (
    IF_CASES_TAC >> simp[]
    >- ( (* contiguous: do_swap ++ [SOPop n] *)
      pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
      imp_res_tac do_swap_prefix_op >>
      simp[EVERY_APPEND, is_prefix_op_def]
    ) >>
    strip_tac >> imp_res_tac popmany_individual_prefix_op
  ) >>
  strip_tac >> imp_res_tac popmany_individual_prefix_op
QED

(* optimistic_swap_plan produces prefix ops *)
Theorem optimistic_swap_plan_prefix_op:
  !dfg inst next_liveness next_is_term ps ops ps'.
    optimistic_swap_plan dfg inst next_liveness next_is_term ps = (ops, ps') ==>
    EVERY is_prefix_op ops
Proof
  rpt gen_tac >>
  simp[optimistic_swap_plan_def] >>
  rpt (CASE_TAC >> simp[]) >>
  strip_tac >> imp_res_tac do_swap_prefix_op
QED

Theorem regular_plan_prefix_wf_gen:
  !liveness dfg cfg fn inst next_liveness is_halting
   next_is_term bb_label ps prefix postfix name ps_out lo.
    generate_regular_inst_plan liveness dfg cfg fn inst
      next_liveness is_halting next_is_term bb_label ps =
      (prefix ++ [SOEmit name] ++ postfix, ps_out) /\
    venom_to_evm_name inst.inst_opcode = SOME name /\
    inst.inst_opcode <> INVOKE /\
    LENGTH (compute_operands inst) <= 16 /\
    LENGTH (compute_operands inst) <=
      LENGTH (SND (emit_input_plan inst.inst_opcode
        (compute_operands inst) next_liveness ps)).ps_stack /\
    (!l. MEM (Label l) (compute_operands inst) ==> IS_SOME (FLOOKUP lo l)) ==>
    prefix_wf lo (LENGTH ps.ps_stack) prefix /\
    EVERY is_prefix_op prefix
Proof
  rpt gen_tac >> strip_tac >>
  `inst.inst_opcode <> JMP` by
    (CCONTR_TAC >> gvs[] >>
     `venom_to_evm_name JMP = NONE` by EVAL_TAC >> fs[]) >>
  `!ltc ps_arg. generate_emit_ops inst ltc ps_arg =
                ([SOEmit name], ps_arg)` by
    simp[generate_emit_ops_def, LET_THM] >>
  fs[generate_regular_inst_plan_def, LET_THM] >>
  pairarg_tac >> gvs[] >>
  gvs[] >>
  `prefix_wf lo (LENGTH ps.ps_stack) input_ops /\
   prefix_end_len lo (LENGTH ps.ps_stack) input_ops =
   LENGTH ps1.ps_stack` by (
    qspecl_then [`compute_operands inst`, `inst.inst_opcode`,
                 `next_liveness`, `ps`, `lo`]
      mp_tac emit_input_plan_wf_len >> simp[]) >>
  Cases_on `is_commutative inst.inst_opcode /\
            LENGTH (compute_operands inst) >= 2` >> gvs[]
  >- (
    pairarg_tac >> gvs[] >>
    pairarg_tac >> gvs[] >>
    pairarg_tac >> gvs[] >>
    pairarg_tac >> gvs[] >>
    qpat_x_assum `(if _ then _ else _) = _` mp_tac >>
    IF_CASES_TAC >> strip_tac >> gvs[]
    >- suspend "comm_lt"
    >> suspend "comm_ge"
  ) >>
  pairarg_tac >> gvs[] >>
  suspend "noncomm"
QED

Resume regular_plan_prefix_wf_gen[comm_lt]:
  (* cost_a < cost_b: reorder_ops resolved to ops_a by gvs *)
  `prefix_wf lo (LENGTH ps1.ps_stack) ops_a` by (
    qspecl_then [`dfg`, `compute_operands inst`, `ps1`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] reorder_plan_wf_len) >> simp[]) >>
  `EVERY is_prefix_op ops_a` by metis_tac[prefix_wf_every_prefix_op] >>
  `EVERY is_prefix_op input_ops` by metis_tac[prefix_wf_every_prefix_op] >>
  qpat_x_assum `(if _ then _ else _) = _` mp_tac >>
  Cases_on `inst.inst_outputs = []` >> simp[]
  >- (
    strip_tac >> gvs[] >>
    `prefix = input_ops ++ ops_a /\ postfix = []` by (
      qspecl_then [`input_ops ++ ops_a`, `SOEmit name`, `[]`,
                   `prefix`, `postfix`] mp_tac append_mid_split_unique >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
    gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
  ) >>
  (* outputs <> []: decompose nested lambdas *)
  IF_CASES_TAC >> simp[]
  >- (
    pairarg_tac >> simp[] >>
    IF_CASES_TAC >> simp[]
    >- (strip_tac >> gvs[] >>
        `prefix = input_ops ++ ops_a /\ postfix = pop_ops` by (
          qspecl_then [`input_ops ++ ops_a`, `SOEmit name`, `pop_ops`,
                       `prefix`, `postfix`] mp_tac append_mid_split_unique >>
          simp[EVERY_APPEND, is_prefix_op_def] >>
          impl_tac >- metis_tac[popmany_plan_prefix_op] >> simp[]) >>
        gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]) >>
    pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
    `EVERY is_prefix_op pop_ops` by metis_tac[popmany_plan_prefix_op] >>
    `EVERY is_prefix_op opt_ops` by metis_tac[optimistic_swap_plan_prefix_op] >>
    `prefix = input_ops ++ ops_a /\ postfix = pop_ops ++ opt_ops` by (
      qspecl_then [`input_ops ++ ops_a`, `SOEmit name`, `pop_ops ++ opt_ops`,
                   `prefix`, `postfix`] mp_tac append_mid_split_unique >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
    gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
  ) >>
  IF_CASES_TAC >> simp[]
  >- (strip_tac >> gvs[] >>
      `prefix = input_ops ++ ops_a /\ postfix = []` by (
        qspecl_then [`input_ops ++ ops_a`, `SOEmit name`, `[]`,
                     `prefix`, `postfix`] mp_tac append_mid_split_unique >>
        simp[EVERY_APPEND, is_prefix_op_def]) >>
      gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]) >>
  pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
  `EVERY is_prefix_op opt_ops` by metis_tac[optimistic_swap_plan_prefix_op] >>
  `prefix = input_ops ++ ops_a /\ postfix = opt_ops` by (
    qspecl_then [`input_ops ++ ops_a`, `SOEmit name`, `opt_ops`,
                 `prefix`, `postfix`] mp_tac append_mid_split_unique >>
    simp[EVERY_APPEND, is_prefix_op_def]) >>
  gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
QED

Resume regular_plan_prefix_wf_gen[comm_ge]:
  (* cost_a >= cost_b: reorder_ops resolved to ops_b by gvs *)
  `LENGTH (TAKE (LENGTH (compute_operands inst) - 2) (compute_operands inst) ++
     [EL (LENGTH (compute_operands inst) - 1) (compute_operands inst);
      EL (LENGTH (compute_operands inst) - 2) (compute_operands inst)])
   = LENGTH (compute_operands inst)` by
    (simp[LENGTH_APPEND, LENGTH_TAKE_EQ] >> decide_tac) >>
  `prefix_wf lo (LENGTH ps1.ps_stack) ops_b` by (
    qspecl_then [`dfg`,
      `TAKE (LENGTH (compute_operands inst) - 2) (compute_operands inst) ++
       [EL (LENGTH (compute_operands inst) - 1) (compute_operands inst);
        EL (LENGTH (compute_operands inst) - 2) (compute_operands inst)]`,
      `ps1`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] reorder_plan_wf_len) >> simp[]) >>
  `EVERY is_prefix_op ops_b` by metis_tac[prefix_wf_every_prefix_op] >>
  `EVERY is_prefix_op input_ops` by metis_tac[prefix_wf_every_prefix_op] >>
  qpat_x_assum `(if _ then _ else _) = _` mp_tac >>
  Cases_on `inst.inst_outputs = []` >> simp[]
  >- (
    strip_tac >> gvs[] >>
    `prefix = input_ops ++ ops_b /\ postfix = []` by (
      qspecl_then [`input_ops ++ ops_b`, `SOEmit name`, `[]`,
                   `prefix`, `postfix`] mp_tac append_mid_split_unique >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
    gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
  ) >>
  IF_CASES_TAC >> simp[]
  >- (
    pairarg_tac >> simp[] >>
    IF_CASES_TAC >> simp[]
    >- (strip_tac >> gvs[] >>
        `prefix = input_ops ++ ops_b /\ postfix = pop_ops` by (
          qspecl_then [`input_ops ++ ops_b`, `SOEmit name`, `pop_ops`,
                       `prefix`, `postfix`] mp_tac append_mid_split_unique >>
          simp[EVERY_APPEND, is_prefix_op_def] >>
          impl_tac >- metis_tac[popmany_plan_prefix_op] >> simp[]) >>
        gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]) >>
    pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
    `EVERY is_prefix_op pop_ops` by metis_tac[popmany_plan_prefix_op] >>
    `EVERY is_prefix_op opt_ops` by metis_tac[optimistic_swap_plan_prefix_op] >>
    `prefix = input_ops ++ ops_b /\ postfix = pop_ops ++ opt_ops` by (
      qspecl_then [`input_ops ++ ops_b`, `SOEmit name`, `pop_ops ++ opt_ops`,
                   `prefix`, `postfix`] mp_tac append_mid_split_unique >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
    gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
  ) >>
  IF_CASES_TAC >> simp[]
  >- (strip_tac >> gvs[] >>
      `prefix = input_ops ++ ops_b /\ postfix = []` by (
        qspecl_then [`input_ops ++ ops_b`, `SOEmit name`, `[]`,
                     `prefix`, `postfix`] mp_tac append_mid_split_unique >>
        simp[EVERY_APPEND, is_prefix_op_def]) >>
      gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]) >>
  pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
  `EVERY is_prefix_op opt_ops` by metis_tac[optimistic_swap_plan_prefix_op] >>
  `prefix = input_ops ++ ops_b /\ postfix = opt_ops` by (
    qspecl_then [`input_ops ++ ops_b`, `SOEmit name`, `opt_ops`,
                 `prefix`, `postfix`] mp_tac append_mid_split_unique >>
    simp[EVERY_APPEND, is_prefix_op_def]) >>
  gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
QED

Resume regular_plan_prefix_wf_gen[noncomm]:
  markerLib.RESUME_TAC >> rpt strip_tac >> (
  (* Both subcases identical: ¬(LENGTH>=2) and ¬is_commutative *)
  `LENGTH (compute_operands inst) <= 16` by decide_tac >>
  `prefix_wf lo (LENGTH ps1.ps_stack) reorder_ops` by (
    qspecl_then [`dfg`, `compute_operands inst`, `ps1`, `lo`]
      mp_tac (REWRITE_RULE [LET_THM] reorder_plan_wf_len) >> simp[]) >>
  `EVERY is_prefix_op reorder_ops` by metis_tac[prefix_wf_every_prefix_op] >>
  `EVERY is_prefix_op input_ops` by metis_tac[prefix_wf_every_prefix_op] >>
  qpat_x_assum `(if _ then _ else _) = _` mp_tac >>
  Cases_on `inst.inst_outputs = []` >> simp[]
  >- (
    strip_tac >> gvs[] >>
    `prefix = input_ops ++ reorder_ops /\ postfix = []` by (
      qspecl_then [`input_ops ++ reorder_ops`, `SOEmit name`, `[]`,
                   `prefix`, `postfix`] mp_tac append_mid_split_unique >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
    gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
  ) >>
  IF_CASES_TAC >> simp[]
  >- (
    pairarg_tac >> simp[] >>
    IF_CASES_TAC >> simp[]
    >- (strip_tac >> gvs[] >>
        `prefix = input_ops ++ reorder_ops /\ postfix = pop_ops` by (
          qspecl_then [`input_ops ++ reorder_ops`, `SOEmit name`, `pop_ops`,
                       `prefix`, `postfix`] mp_tac append_mid_split_unique >>
          simp[EVERY_APPEND, is_prefix_op_def] >>
          impl_tac >- metis_tac[popmany_plan_prefix_op] >> simp[]) >>
        gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]) >>
    pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
    `EVERY is_prefix_op pop_ops` by metis_tac[popmany_plan_prefix_op] >>
    `EVERY is_prefix_op opt_ops` by metis_tac[optimistic_swap_plan_prefix_op] >>
    `prefix = input_ops ++ reorder_ops /\ postfix = pop_ops ++ opt_ops` by (
      qspecl_then [`input_ops ++ reorder_ops`, `SOEmit name`,
                   `pop_ops ++ opt_ops`,
                   `prefix`, `postfix`] mp_tac append_mid_split_unique >>
      simp[EVERY_APPEND, is_prefix_op_def]) >>
    gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]
  ) >>
  IF_CASES_TAC >> simp[]
  >- (strip_tac >> gvs[] >>
      `prefix = input_ops ++ reorder_ops /\ postfix = []` by (
        qspecl_then [`input_ops ++ reorder_ops`, `SOEmit name`, `[]`,
                     `prefix`, `postfix`] mp_tac append_mid_split_unique >>
        simp[EVERY_APPEND, is_prefix_op_def]) >>
      gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append]) >>
  pairarg_tac >> simp[] >> strip_tac >> gvs[] >>
  `EVERY is_prefix_op opt_ops` by metis_tac[optimistic_swap_plan_prefix_op] >>
  `prefix = input_ops ++ reorder_ops /\ postfix = opt_ops` by (
    qspecl_then [`input_ops ++ reorder_ops`, `SOEmit name`, `opt_ops`,
                 `prefix`, `postfix`] mp_tac append_mid_split_unique >>
    simp[EVERY_APPEND, is_prefix_op_def]) >>
  gvs[EVERY_APPEND] >> metis_tac[prefix_wf_append])
QED

Finalise regular_plan_prefix_wf_gen;
